import type { Locale } from './types';

const pt = {
  meta: {
    title: 'Marcos Cantelli · Analista de BI | Dados, CI/CD e Cloud',
    description:
      'Currículo de Marcos Vinícius Rodrigues Cantelli: Analista de BI no Bradesco, com experiência em SQL Server, Databricks, CI/CD (GitHub Actions, Jenkins), Linux, Terraform e Azure.',
  },
  skipLink: 'Pular para o conteúdo',
  nav: {
    label: 'Seções',
    about: 'Sobre',
    experience: 'Experiência',
    certifications: 'Certificações',
    skills: 'Competências',
    projects: 'Projetos',
    courses: 'Cursos',
    contact: 'Contato',
    menu: 'Abrir menu',
    close: 'Fechar menu',
  },
  theme: { toggle: 'Alternar tema claro/escuro' },
  lang: { switch: 'English', switchLabel: 'View this page in English', short: 'EN' },
  hero: { download: 'Baixar currículo (PDF)', contact: 'Entrar em contato' },
  sections: {
    about: 'Sobre mim',
    education: 'Formação',
    experience: 'Experiência',
    certifications: 'Certificações',
    skills: 'Competências',
    projects: 'Projetos',
    technicalProjects: 'Projetos técnicos',
    academicProjects: 'Projetos acadêmicos (FIAP)',
    courses: 'Cursos',
    contact: 'Contato',
  },
  cert: { inProgress: 'Em preparação', verify: 'Ver credencial' },
  projects: { viewGithub: 'Ver no GitHub' },
  courses: { view: 'Ver certificado', viewProfile: 'Ver perfil' },
  contact: {
    intro: 'Quer conversar sobre uma vaga ou projeto? Envie uma mensagem pelo formulário.',
    name: 'Nome',
    email: 'E-mail',
    company: 'Empresa',
    optional: 'opcional',
    message: 'Mensagem',
    submit: 'Enviar mensagem',
    sending: 'Enviando…',
    success: 'Mensagem enviada! Obrigado pelo contato, responderei em breve.',
    elsewhere: 'Também estou em',
    errors: {
      name: 'Informe seu nome (2 a 100 caracteres).',
      email: 'Informe um e-mail válido.',
      company: 'O nome da empresa deve ter no máximo 120 caracteres.',
      message: 'A mensagem deve ter entre 10 e 5000 caracteres.',
      captcha: 'Confirme a verificação anti-spam e tente novamente.',
      rate_limited: 'Muitas mensagens em pouco tempo. Tente novamente mais tarde.',
      server: 'Não foi possível enviar agora. Tente novamente em alguns minutos.',
      network: 'Falha de conexão. Verifique sua internet e tente novamente.',
    },
  },
  footer: {
    rights: 'Marcos Cantelli',
  },
  newTab: '(abre em nova aba)',
  notFound: {
    title: 'Página não encontrada',
    text: 'O endereço acessado não existe.',
    back: 'Voltar ao início',
  },
};

export type UI = typeof pt;

const en: UI = {
  meta: {
    title: 'Marcos Cantelli · BI Analyst | Data, CI/CD & Cloud',
    description:
      'Résumé of Marcos Vinícius Rodrigues Cantelli: BI Analyst at Bradesco with experience in SQL Server, Databricks, CI/CD (GitHub Actions, Jenkins), Linux, Terraform and Azure.',
  },
  skipLink: 'Skip to content',
  nav: {
    label: 'Sections',
    about: 'About',
    experience: 'Experience',
    certifications: 'Certifications',
    skills: 'Skills',
    projects: 'Projects',
    courses: 'Courses',
    contact: 'Contact',
    menu: 'Open menu',
    close: 'Close menu',
  },
  theme: { toggle: 'Toggle light/dark theme' },
  lang: { switch: 'Português', switchLabel: 'Ver esta página em português', short: 'PT' },
  hero: { download: 'Download résumé (PDF)', contact: 'Get in touch' },
  sections: {
    about: 'About me',
    education: 'Education',
    experience: 'Experience',
    certifications: 'Certifications',
    skills: 'Skills',
    projects: 'Projects',
    technicalProjects: 'Technical projects',
    academicProjects: 'Academic projects (FIAP)',
    courses: 'Courses',
    contact: 'Contact',
  },
  cert: { inProgress: 'In preparation', verify: 'View credential' },
  projects: { viewGithub: 'View on GitHub' },
  courses: { view: 'View certificate', viewProfile: 'View profile' },
  contact: {
    intro: 'Want to talk about a role or a project? Send me a message using the form.',
    name: 'Name',
    email: 'Email',
    company: 'Company',
    optional: 'optional',
    message: 'Message',
    submit: 'Send message',
    sending: 'Sending…',
    success: 'Message sent! Thanks for reaching out, I will reply soon.',
    elsewhere: 'You can also find me on',
    errors: {
      name: 'Please enter your name (2 to 100 characters).',
      email: 'Please enter a valid email address.',
      company: 'Company name must be at most 120 characters.',
      message: 'The message must be between 10 and 5000 characters.',
      captcha: 'Please complete the anti-spam check and try again.',
      rate_limited: 'Too many messages in a short time. Please try again later.',
      server: 'Could not send right now. Please try again in a few minutes.',
      network: 'Connection failed. Check your internet connection and try again.',
    },
  },
  footer: {
    rights: 'Marcos Cantelli',
  },
  newTab: '(opens in a new tab)',
  notFound: {
    title: 'Page not found',
    text: 'The address you requested does not exist.',
    back: 'Back to home',
  },
};

export const ui: Record<Locale, UI> = { pt, en };
